directories:
  output: electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: com.demosql.app
productName: demosql
copyright: 北京八号地信息技术有限公司 © 2021
publish:
  - provider: generic
    url: 'http://locald.in.com'
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: ./public/icons/icon.icns
  artifactName: '${productName}_setup_${version}.${ext}'
nsis:
  oneClick: false
  perMachine: true
  allowElevation: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  runAfterFinish: true
win:
  icon: ./public/icons/icon.ico
  artifactName: '${productName}_setup_${version}.${ext}'
  target:
    - target: nsis
      arch:
        - x64
        - ia32
linux:
  icon: ./public/icons
  artifactName: '${productName}_setup.${ext}'
  category: office
electronVersion: 8.5.5
